### ISSUE TITLE
抽不了水

### ISSUE THREAD

**Issue by alexljk** [wbdy95/MinerProxy#11]
我用的是币安的池但是运行了2小时以上 也没有抽到水，会不会是因为币安是 用的 用户名的问题 不是钱包地址

**Comment by wbdy95** [comment]
你是直接抽水道币安的还是 ？

**Comment by alexljk** [comment]
是的 抽水到币安

**Comment by wbdy95** [comment]
你先把抽水的抽到E池或者其他池子把。币安的还有点问题。
