### ISSUE TITLE
centos下抽水老是 失败devFee矿池连接失败:EOF

### ISSUE THREAD

**Issue by hadesya** [wbdy95/MinerProxy#6]
centos下抽水老是 失败devFee矿池连接失败:EOF，难得有一次成功

**Comment by wbdy95** [comment]
换乌班图吧

**Comment by hadesya** [comment]
难道是 阿里和腾讯云的问题  你用的是哪个运营商

**Comment by hadesya** [comment]
> 换乌班图吧

难道是阿里和腾讯云的问题你用的是哪个运营商，乌班图也一样

**Comment by wbdy95** [comment]
我用的恒天云，目前没有问题，配置是4核8G，5mbps带宽

**Comment by hadesya** [comment]
地址来个看看。。他这个是不是没有内网 直接外网的

**Comment by hadesya** [comment]
> 我用的恒天云，目前没有问题，配置是4核8G，5mbps带宽

地址来个看看。。他这个是不是没有内网 直接外网的

**Comment by wbdy95** [comment]
154.204.56.1
这个ip段

**Comment by hadesya** [comment]
> 恒天云

恒天云网址

**Comment by wbdy95** [comment]
https://my.htstack.com/aff.php?aff=4044

**Comment by hadesya** [comment]
> https://my.htstack.com/aff.php?aff=4044

你的研究下来了 阿里和腾讯为什么会出这个问题

**Comment by wbdy95** [comment]
阿里和腾讯 应该在打击挖矿行为，限制了挖矿的网络

**Comment by hadesya** [comment]
> 阿里和腾讯 应该在打击挖矿行为，限制了挖矿的网络
挖矿正常 就是抽不正常

**Comment by wbdy95** [comment]
按道理说不应该的。

**Comment by hadesya** [comment]
> 按道理说不应该的。
问题是现在就是这样

**Comment by wbdy95** [comment]
对了你试试把抽水的地址改成币印或者E池或者其他的池子试试。

**Comment by hadesya** [comment]
鱼池也是 ok也是


> 对了你试试把抽水的地址改成币印或者E池或者其他的池子试试。

**Comment by wbdy95** [comment]
不要抽到国内的池子里去，

**Comment by hadesya** [comment]
本身就没有多少算例 抽到那边都那不出来

**Comment by wbdy95** [comment]
币印可以出来，每天自动兑换成usdt

**Comment by hadesya** [comment]
> 币印

是要注册 还是匿名啊

**Comment by hadesya** [comment]
> > 币印
> 
> 是要注册 还是匿名啊

有交流的群吗

**Comment by wbdy95** [comment]
有电报交流群

**Comment by hadesya** [comment]
> 有电报交流群

电报注册不了啊

**Comment by hadesya** [comment]
> > 有电报交流群
> 
> 电报注册不了啊

2021/12/21 20:47:24 devFee矿池连接失败:EOF 用币印 还是一样

**Comment by wbdy95** [comment]
留个联系方式我远程你看看

**Comment by hadesya** [comment]
967 527 837 向日葵

**Comment by wbdy95** [comment]
大概晚上11点可以么

**Comment by hadesya** [comment]
> 大概晚上11点可以么

可以
